-- Create words table if it doesn't exist (run once)
CREATE TABLE IF NOT EXISTS words (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  word text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

-- Seed words
INSERT INTO words (word) VALUES
  ('reward'),
  ('shiver'),
  ('regret'),
  ('carbon'),
  ('island'),
  ('impound'),
  ('extreme'),
  ('inspire'),
  ('finance'),
  ('control'),
  ('collapse'),
  ('medicine'),
  ('frighten'),
  ('observer'),
  ('classify'),
  ('monstrous'),
  ('orchestra'),
  ('executive'),
  ('fireplace'),
  ('essential'),
  ('prevalence'),
  ('background'),
  ('particular'),
  ('attraction'),
  ('pedestrian'),
  ('unfortunate'),
  ('charismatic'),
  ('institution'),
  ('destruction'),
  ('presentation'),
  ('manufacturer'),
  ('interference'),
  ('announcement'),
  ('presidential'),
  ('inappropriate'),
  ('embarrassment'),
  ('consideration'),
  ('comprehensive'),
  ('communication'),
  ('representative'),
  ('responsibility'),
  ('constitutional'),
  ('discrimination'),
  ('recommendation')
ON CONFLICT (word) DO NOTHING;
